export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const GETCITYLIST = "GETCITYLIST";
export const GETCOUNTYLIST = "GETCOUNTYLIST";
export const GETPARAMETER = "GETPARAMETER";
export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
export const SHOW_STATUS_MESSAGE = "SHOW_STATUS_MESSAGE";
export const CHANGE_SELECTED_CITY_ID = "CHANGE_SELECTED_CITY_ID";
